### ISSUE TITLE
Angularjs: orderBy().toLiveArray() produces exception

### ISSUE THREAD

**Issue by rbuergi** [jaystack/jaydata#150]
A simple orderBy with .toLiveArray() in angularjs produces and exception. It uses odata to web api.

Here is my code:

$scope.data = context['Things']
    .orderBy("DisplayName")
    .toLiveArray();

Stack trace:

TypeError: Cannot call method 'parseCode' of undefined
    at CodeParser.$C.parseExpression (http://localhost:53017/bundles/jaydata.js:1:151097)
    at CodeParser.$C.createExpression (http://localhost:53017/bundles/jaydata.js:1:151370)
    at QueryExpressionCreator.$C.VisitCodeExpression (http://localhost:53017/bundles/jaydata.js:1:207778)
    at QueryExpressionCreator.$C.Visit (http://localhost:53017/bundles/jaydata.js:1:195826)
    at QueryExpressionCreator.$C.VisitOrderExpression (http://localhost:53017/bundles/jaydata.js:1:209179)
    at QueryExpressionCreator.$C.Visit (http://localhost:53017/bundles/jaydata.js:1:195826)
    at QueryExpressionCreator.$C.VisitToArrayExpression (http://localhost:53017/bundles/jaydata.js:1:195919)
    at QueryExpressionCreator.$C.Visit (http://localhost:53017/bundles/jaydata.js:1:195826)
    at Queryable.$data.Class.define.toTraceString (http://localhost:53017/bundles/jaydata.js:1:283099)
    at Queryable.$data.Queryable.toLiveArray (http://localhost:53017/bundles/jaydata.js:1:422412)

**Comment by rbuergi** [comment]
I noticed that this is due to lacking AMD support. I included the scripts via require.js. Once I put the scripts in the header, all works fine. Is AMD support planned? When is it coming?
