### ISSUE TITLE
Unhandled exception in JaySvcUtil

### ISSUE THREAD

**Issue by billbak** [jaystack/jaydata#193]
The provider comes from a partner, I redacted their name in the text below.  I tried this with and without quotes around the URL.  I get the same output either way.  I then saw the -username and -password arguments and supplied them, but got the same output.  Based on the text below I am guessing it can't open the URL.  I can open this in a browser and in my code.  Thanks.

C:\JayData>JaySvcUtil -metadataUri="http://----------.cloudapp.net/--------/odata/$metadata"
Requesting: etadataUri=http://----------.cloudapp.net/--------/odata/$metadata..
.
Unhandled Exception: System.NotSupportedException: The given path's format is not supported.
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,FileShare share)
   at System.IO.File.OpenRead(String path)
   at JaySvcUtil.Program.Main(String[] args)

**Comment by billbak** [comment]
Ok, I skipped around this problem by using $data.service ().  I'm getting some warnings about missing inverseProperty's.  As mentioned above, the service comes from a partner, so I have to speak to them about this issue.  I'm a little surprised that the library is very chatty.  As soon as I hit my require statement (this is node.js) I see:  (Again I redacted strings specific to the partner.)

Should be empty: []

Once I call $data.service () I see:

Info: generating type ---------.--------.DataService.Models.----------------------
Info: generating type ---------.--------.DataService.Models.-----------
Etc...

The first one looks sort-of like the output of an assert.  The next several lines are just progress statements.  I'm off to see if I can find anything in the docs to turn down the verbosity.  But if anyone knows how, please mention it here.  Thanks!

**Comment by dellinger** [comment]
As a note, I am getting the exact same error from a different source.
