### ISSUE TITLE
node.js oData with sqLite data provider

### ISSUE THREAD

**Issue by pspaulding** [jaystack/jaydata#86]
Does JayData support using sqLite as an oData provider from node.js?  I've followed the example at http://jaydata.org/blog/install-your-own-odata-server-with-nodejs-and-mongodb that uses mongoDB as the database server, substituting sqLite in the appropriate places and am using a very simple test database with one table and two fields.  

This is my test model:

``` js
$data.Class.define('purchase_orders', $data.Entity, null, {
  "id": {
    "type": "integer",
    "required": true,
    "key": true
  },
  "name": {
    "type": "string",
    "required": true,
    "maxLength": 50
  }
}, null);

$data.Class.defineEx("context", [$data.EntityContext, $data.ServiceBase], null, {
    purchase_orders: {type: $data.EntitySet, elementType: purchase_orders}
});
exports = context;
```

The service Url looks good:

``` xml
<service xmlns:atom="http://www.w3.org/2005/Atom" xmlns="http://www.w3.org/2007/app" atom:source="JayStrom" xml:base="http://localhost:8080/odata/">
<workspace>
<atom:title>Default</atom:title>
<collection href="purchase_orders">
<atom:title>purchase_orders</atom:title>
</collection>
</workspace>
</service>
```

And the $metadata Url looks good:

``` xml
<edmx:Edmx xmlns:edmx="http://schemas.microsoft.com/ado/2007/06/edmx" Version="1.0">
<edmx:DataServices xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:DataServiceVersion="1.0" m:MaxDataServiceVersion="2.0">
<Schema xmlns="http://schemas.microsoft.com/ado/2008/09/edm" Namespace="MyContext">
<EntityType Name="purchase_orders">
<Key>
<PropertyRef Name="id"/>
</Key>
<Property Name="id" Nullable="false" Type="Edm.Int32"/>
<Property MaxLength="50" Name="name" Nullable="false" Type="Edm.String"/>
</EntityType>
<EntityContainer m:IsDefaultEntityContainer="true" Name="context">
<EntitySet EntityType="MyContext.purchase_orders" Name="purchase_orders"/>
</EntityContainer>
</Schema>
</edmx:DataServices>
</edmx:Edmx>
```

But when I try accessing the service from the browser:

``` js
$data.service('/odata', function (contextFactory, contextType) {
    context = contextFactory();
    context.purchase_orders.toArray(function(po){console.log(po);})
});
```

I get the following exception in node.js:

``` console
ReferenceError: SqlStatementBlocks is not defined
    at SqlPagingCompiler.$C.VisitConstantExpression (E:\odata_test\node_modules\jaydata\lib\Types\StorageProviders\SqLite\SqlPagingCompiler.js:13:28)
    at SqlPagingCompiler.$C.Visit (E:\odata_test\node_modules\jaydata\lib\Types\Expressions\EntityExpressions\EntityExpressionVisitor.js:18:29)
    at SqlPagingCompiler.$C.VisitPagingExpression (E:\odata_test\node_modules\jaydata\lib\Types\StorageProviders\SqLite\SqlPagingCompiler.js:9:14)
    at SqlPagingCompiler.$C.Visit (E:\odata_test\node_modules\jaydata\lib\Types\Expressions\EntityExpressions\EntityExpressionVisitor.js:18:29)
    at SqlCompiler.$C.VisitPagingExpression (E:\odata_test\node_modules\jaydata\lib\Types\StorageProviders\SqLite\SqLiteCompiler.js:113:24)
    at SqlCompiler.$C.Visit (E:\odata_test\node_modules\jaydata\lib\Types\Expressions\EntityExpressions\EntityExpressionVisitor.js:18:29)
    at SqlCompiler.$C.VisitToArrayExpression (E:\odata_test\node_modules\jaydata\lib\Types\StorageProviders\SqLite\SqLiteCompiler.js:70:14)
    at SqlCompiler.$C.Visit (E:\odata_test\node_modules\jaydata\lib\Types\Expressions\EntityExpressions\EntityExpressionVisitor.js:18:29)
    at SqlCompiler.$C.compile (E:\odata_test\node_modules\jaydata\lib\Types\StorageProviders\SqLite\SqLiteCompiler.js:46:14)
    at SQLiteCompiler.$C.compile (E:\odata_test\node_modules\jaydata\lib\Types\StorageProviders\SqLite\SqLiteCompiler.js:260:18)
```

Any ideas?  If JayData does not support sqlite in this manner, any idea when support would be added (mysql would be even better)?

Thanks

**Comment by agdolla** [comment]
Hi
We had a working prototype to use sqlite with nodejs on the server side. It was really slow, especially compared to mongodb so nobody really used it and we stopped maintaining it, that is why it does not work now. We do support sqlite on the client side (browser). If you need sqlite in nodejs we can fix it and you can use it, but it will be slow.
We do plan to support many sql database servers on the server side including mysql but there is very little pressure on us to do that, our clients either want to use JayData to access local databases in the browser or they use oData with Entity Framework, WebApi, SAP, etc. So we concentrate our forces to improve JayData in those areas with many new features.
If you really need mysql support then:
- you can implement it yourself, JayData is an open source library
- have other users with this need so we'd feel the pressure
- buy support from us and finance the development of the feature that you need

**Comment by pspaulding** [comment]
Thanks for the reply.
